version: '3'

services:

  comments:
    build: ./comments
    container_name: comments
    command: npm start
    ports:
      - 4001:4001
    depends_on:
      - 'event-bus'

  event-bus:
    build: ./event-bus
    container_name: event-bus
    command: npm start
    ports:
      - 4005:4005
    depends_on:
      - 'mongodb'

  moderation:
    build: ./moderation
    container_name: moderation
    command: npm start
    ports:
      - 4003:4003
    depends_on:
      - 'event-bus'

  posts:
    build: ./posts
    container_name: posts
    command: npm start
    ports:
      - 4000:4000
    depends_on:
      - 'event-bus'

  query:
    build: ./query
    container_name: query
    command: npm start
    ports:
      - 4002:4002
    depends_on:
      - 'event-bus'

  db-client:
    build: ./db-client
    container_name: db-client
    command: npm start
    ports:
      - 3001:3001
    depends_on:
      - 'mongodb'

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - 'mongodb'

volumes:
  mongo-data:
    driver: local
